<template>
  <b-container fluid>
    <b-row>
      <div class="col-sm-12">
        <div
          class="iq-card position-relative inner-page-bg bg-primary"
          style="height: 150px;"
        >
          <div class="inner-page-title">
            <h3 class="text-white">
              Font Awwsome
            </h3>
            <p class="text-white">
              lorem ipsum
            </p>
          </div>
        </div>
      </div>
      <b-col sm="12">
        <iq-card>
          <template v-slot:headerTitle>
            <h4 class="card-title">
              Fontawesome Icon
            </h4>
          </template>
          <template v-slot:body>
            <p>Use Class <code>&lt;i class="fa fa-address-book"&gt;&lt;/i&gt;</code></p>
            <b-row class="mt-3">
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-address-book"
                    aria-hidden="true"
                  />address-book
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-envelope-open"
                    aria-hidden="true"
                  />envelope-open
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-id-card"
                    aria-hidden="true"
                  />id-card
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-telegram"
                    aria-hidden="true"
                  />telegram
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-user-circle"
                    aria-hidden="true"
                  />user-circle
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-area-chart"
                    aria-hidden="true"
                  />area-chart
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-asterisk"
                    aria-hidden="true"
                  />asterisk
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-car"
                    aria-hidden="true"
                  />car
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-bars"
                    aria-hidden="true"
                  />bars
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-battery-full"
                    aria-hidden="true"
                  />battery-full
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-bluetooth"
                    aria-hidden="true"
                  />bluetooth
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-book"
                    aria-hidden="true"
                  />book
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-bug"
                    aria-hidden="true"
                  />bug
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-building"
                    aria-hidden="true"
                  />building
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-calculator"
                    aria-hidden="true"
                  />calculator
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-calendar"
                    aria-hidden="true"
                  />calendar
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-camera"
                    aria-hidden="true"
                  />camera
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-commenting"
                    aria-hidden="true"
                  />commenting
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-crop"
                    aria-hidden="true"
                  />crop
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-download"
                    aria-hidden="true"
                  />download
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-folder"
                    aria-hidden="true"
                  />folder
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-gift"
                    aria-hidden="true"
                  />gift
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-users"
                    aria-hidden="true"
                  />users
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-hashtag"
                    aria-hidden="true"
                  />hashtag
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-home"
                    aria-hidden="true"
                  />home
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-lock"
                    aria-hidden="true"
                  />lock
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-graduation-cap"
                    aria-hidden="true"
                  />graduation-cap
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-paper-plane"
                    aria-hidden="true"
                  />paper-plane
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-star"
                    aria-hidden="true"
                  />star
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-tag"
                    aria-hidden="true"
                  />tag
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-trash"
                    aria-hidden="true"
                  />trash
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-upload"
                    aria-hidden="true"
                  />upload
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-university"
                    aria-hidden="true"
                  />university
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-wifi"
                    aria-hidden="true"
                  />wifi
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-thumbs-up"
                    aria-hidden="true"
                  />thumbs-up
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-train"
                    aria-hidden="true"
                  />train
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-file"
                    aria-hidden="true"
                  />file
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-snapchat"
                    aria-hidden="true"
                  />snapchat
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-twitter"
                    aria-hidden="true"
                  />twitter
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-wordpress"
                    aria-hidden="true"
                  />wordpress
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-wordpress"
                    aria-hidden="true"
                  />wordpress
                </b-link>
              </b-col>
              <b-col
                lg="2"
                md="2"
                sm="2"
              >
                <b-link
                  class="iq-icons-list"
                  href="#"
                >
                  <i
                    class="fa fa-wordpress"
                    aria-hidden="true"
                  />wordpress
                </b-link>
              </b-col>
              <b-col
                sm="12"
                class="text-center mt-3"
              >
                <b-link
                  href="https://fontawesome.com/v4.7.0/"
                  target="blank"
                  class="btn btn-primary"
                >
                  View All Icon
                </b-link>
              </b-col>
            </b-row>
          </template>
        </iq-card>
      </b-col>
    </b-row>
  </b-container>
</template>

<script>
import { socialvue } from '../../config/pluginInit'
export default {
  name: 'IconFontAwesome5',
  mounted () {
    socialvue.index()
  }
}
</script>
